
service: game-stat-scheduler

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs14.x

functions:
  gameStatHander:
    handler: game-stat-scheduler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
  cronHandler:
    handler: game-stat-scheduler.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0/2 * ? * MON-FRI *)

plugins:
  - serverless-plugin-typescript